name: migration_scripts
description: Scripts de migração para o aplicativo K_Photo

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  path: ^1.9.0
  process_run: ^0.13.3

dev_dependencies:
  lints: ^3.0.0
